# Generated by Django 5.0.2 on 2024-06-02 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='survey',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.answer'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
