# Generated by Django 5.0.2 on 2024-06-02 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.TextField(default='', null=True, verbose_name='성별')),
                ('ageGrp', models.IntegerField(default=0, null=True, verbose_name='나이대')),
                ('travelStyl1', models.IntegerField(default=0, null=True, verbose_name='장소')),
                ('travelStyl2', models.IntegerField(default=0, null=True, verbose_name='기간')),
                ('travelStyl3', models.IntegerField(default=0, null=True, verbose_name='숙소')),
                ('travelStyl4', models.IntegerField(default=0, null=True, verbose_name='활동')),
                ('travelStyl5', models.IntegerField(default=0, null=True, verbose_name='방문지')),
                ('travelStyl6', models.IntegerField(default=0, null=True, verbose_name='계획')),
                ('travelStyl7', models.IntegerField(default=0, null=True, verbose_name='사진')),
                ('travelStyl8', models.IntegerField(default=0, null=True, verbose_name='동반자')),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
